### ISSUE TITLE
Another Code Question

### ISSUE THREAD

**Issue by megantuttle** [Alexanderallenbrown/MotionBase#8]
@wangzeyi are you sure you should have converted ax, ay, and az in the traj.m function?  Did you assume that those values were in degrees since there were a couple numbers greater than 1?

**Comment by wangzeyi** [comment]
@megantuttle  I am not sure. Ask @Alexanderallenbrown

**Comment by wangzeyi** [comment]
I saw a few numbers greater than 3, so I assumed that they are in degrees.
They are really small angles if they are in degrees though

**Comment by Alexanderallenbrown** [comment]
Guys,

I will have to look at the data after we get back into Easton, but "ax,ay,az" should be accelerations, so they are either in gs or in m/s^2. 

If there are angles in the file that you are using, they could either be in degrees or radians. I imagine that the roll (x) tilt of the vehicle was always less than 5 degrees max-min. The z angle should tell you the most, since I went around an on ramp and had an angular change in z of about 270 degrees over the course of the file.

**Comment by Alexanderallenbrown** [comment]
I see now that traj.m takes angles and not accelerations called ax,ay,az. 

Angles in the data file were probably in degrees. The checks I mentioned will help confirm.
